name: Workflow for Codecov
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Install dependencies
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - name: Run tests and collect coverage
      run: mvn -B test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4-beta
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
